
FROM envoyproxy/envoy:latest
MAINTAINER Thanasis Tryfonos <thanasistryfonos@gmail.com>
RUN apt-get update \
 && apt-get -y install software-properties-common
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer
COPY envoy_jservice.json /etc/envoy.json
COPY start_jservice.sh /home/start_jservice.sh
RUN chmod +x /home/start_jservice.sh
COPY service1-0.0.1-SNAPSHOT.jar /home/service1-0.0.1-SNAPSHOT.jar
EXPOSE 80
ENTRYPOINT ["/home/start_jservice.sh"]
# CMD /usr/local/bin/envoy -c /etc/envoy.json --service-cluster jservice
