
FROM lyft/envoy:latest
MAINTAINER Thanasis Tryfonos <thanasistryfonos@gmail.com>
#install java8
RUN apt-get update \
 && apt-get -y install software-properties-common
# && add-apt-repository -y ppa:webupd8team/java \
# && apt-get update \
# RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
# RUN apt-get install -y oracle-java8-installer
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

COPY start_jservice.sh /home/start_jservice.sh
RUN chmod +x /home/start_jservice.sh
COPY service1-0.0.1-SNAPSHOT.jar /home/service1-0.0.1-SNAPSHOT.jar
EXPOSE 8001
# ENTRYPOINT ["/bin/bash","-c","/tmp/start_jservice.sh"]
# CMD ["java", "-jar", "/tmp/service1-0.0.1-SNAPSHOT.jar"]
ENTRYPOINT ["/home/start_jservice.sh"]
