# FROM alpine
# RUN apk update && apk add openjdk8-jre
# ADD service1-0.0.1-SNAPSHOT.jar /home/service1-0.0.1-SNAPSHOT.jar
# EXPOSE 8001
# CMD ["java", "-jar", "/home/service1-0.0.1-SNAPSHOT.jar"]
FROM lyft/envoy:latest
RUN apt-get -y update && apt install -y default-jre
#COPY envoy.json /etc/envoy.json
COPY service1-0.0.1-SNAPSHOT.jar /home/service1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/home/service1-0.0.1-SNAPSHOT.jar"]
CMD /usr/local/bin/envoy -c /etc/envoy.json
